theme: jekyll-theme-time-machine
title: "RV Travel Data Analysis App"
description: &description "Website that hosts Team RVago's project abstract, poster and video"
github:
  is_project_page: false
teaser: "RVagoWebapp.png"
