theme: jekyll-theme-leap-day
title: "RV Travel Data Analysis App"
description: &description "Website that hosts Team RVago's Senior Design project abstract, poster and video"
github:
  is_project_page: false
teaser: "RVagoWebapp.png"
